export const EXERCISE_CATEGORIES = {
    "Peitoral": [
        "Supino Reto (Barra/Halteres/Smith)",
        "Supino Inclinado (Barra/Halteres/Smith)",
        "Supino Declinado (Barra/Halteres)",
        "Supino Guilhotina (Neck Press)",
        "Floor Press (Supino no Chão)",
        "Squeeze Press (Halteres)",
        "Supino Vertical (Máquina)",
        "Supino Máquina (Pico Contração)",
        "Crucifixo Reto (Halteres)",
        "Crucifixo Inclinado (Halteres)",
        "Crucifixo Declinado (Halteres)",
        "Crucifixo no Voador",
        "Crossover (Polia Alta)",
        "Crossover (Polia Baixa)",
        "Crossover (Polia Média)",
        "Peck Deck (Voador)",
        "Pullover com Halter",
        "Flexão Clássica",
        "Flexão Diamante",
        "Flexão Declinada",
        "Mergulho nas Paralelas (Dips)",
        "Paralela Fechada"
    ],
    "Dorsais": [
        "Barra Fixa (Pronada/Aberta)",
        "Barra Fixa (Supinada/Chin-up)",
        "Barra Fixa (Neutra)",
        "Puxada Alta (Polia) Frente",
        "Puxada Alta (Polia) Costas",
        "Puxada Triângulo",
        "Puxada Lateral Unilateral",
        "Pulldown Articulado (Máquina)",
        "Pulley Puxada Frente (Aberta)",
        "Pulley Puxada Frente (Fechada Supinada)",
        "Pulley Puxada Frente (Barra Romana)",
        "Remada Curvada (Barra - Pronada)",
        "Remada Curvada (Barra - Supinada/Yates Row)",
        "Remada Cavalinho (T-Bar Row)",
        "Remada Cavalinho (Landmine)",
        "Remada Serrote (Unilateral com Halter)",
        "Remada Baixa (Triângulo/Cabo)",
        "Remada Pendlay",
        "Remada Máquina (Pegada Aberta Pronada)",
        "Kroc Rows",
        "Meadows Row",
        "Levantamento Terra (Deadlift)",
        "Meio-Terra (Rack Pull)",
        "Hiperextensão Lombar (Banco Romano)",
        "Flexora Lombar",
        "Lombar Solo",
        "Good Morning",
        "Bom Dia",
        "Pulldown com Corda (Braços estendidos)",
        "Pull Over (Halter/Corda)",
        "Transformers (Pegada Neutra)"
    ],
    "Membros Inferiores": [
        "Agachamento Livre (Back Squat)",
        "Agachamento Livre (Barra Alta)",
        "Agachamento Frontal (Front Squat)",
        "Agachamento Zercher",
        "Agachamento Smith",
        "Agachamento Máquina",
        "Agachamento Sumô",
        "Agachamento Sissy",
        "Leg Press 45º",
        "Leg Press Horizontal",
        "Hack Machine",
        "Agachamento Búlgaro",
        "Passada / Avanço (Walking Lunge)",
        "Cadeira Extensora",
        "Cadeira Extensora (Unilateral)",
        "Sissy Squat",
        "Step-up (Subida no Banco)",
        "Subida no Banco (Box Uni)",
        "Stiff (Barra/Halteres)",
        "Levantamento Terra Romeno (RDL)",
        "Levantamento Terra Sumô",
        "Mesa Flexora (Deitado)",
        "Cadeira Flexora (Sentado)",
        "Flexora em Pé (Máquina/Caneleira)",
        "Elevação Pélvica (Hip Thrust)",
        "Elevação Pélvica Máquina",
        "Elevação Pélvica Solo Unilateral",
        "Glúteo Cabo (Coice)",
        "Glúteo Coice Máquina",
        "Glúteo Coice Cross",
        "Glúteo 4 Apoios (Banco Reto)",
        "Abdutor Cross",
        "Cross Perna Estendida",
        "Cadeira Abdutora",
        "Cadeira Adutora",
        "Gêmeos em Pé (Máquina/Smith)",
        "Panturrilha em Pé Máquina",
        "Panturrilha Sentada",
        "Panturrilha Livre",
        "Gêmeos Sentado (Máquina)",
        "Gêmeos no Leg Press",
        "Burrinho (Donkey Calf Raise)"
    ],
    "Ombros": [
        "Desenvolvimento Militar (OHP)",
        "Desenvolvimento com Halteres (Sentado)",
        "Desenvolvimento Arnold",
        "Desenvolvimento Nuca",
        "Desenvolvimento Máquina",
        "Desenvolvimento Barra (Sentado)",
        "Elevação Frontal (Halter/Barra/Corda)",
        "Elevação Frontal Barra (W no Banco)",
        "Elevação Lateral (Halteres)",
        "Elevação Lateral na Polia (Cabo)",
        "Remada Alta (Upright Row)",
        "Remada Alta (Barra)",
        "Remada Alta Fechada Cross",
        "Crucifixo Inverso (Halteres)",
        "Crucifixo Inverso (Voador)",
        "Voador Inverso (Peck Deck Invertido)",
        "Face Pull (Corda)",
        "Encolhimento (Barra/Halteres - Shrugs)",
        "Encolhimento Halteres",
        "Encolhimento Smith",
        "Encolhimento Lee Haney",
        "Manguito Rotador (Mobilidade)",
        "Manguito Cross"
    ],
    "Braços": [
        "Tríceps Testa (Skullcrusher)",
        "Tríceps Testa Halteres",
        "Tríceps Francês",
        "Tríceps Pulley (Polia)",
        "Tríceps Corda",
        "Tríceps Corda (Cross)",
        "Tríceps Coice (Kickback)",
        "Tríceps Máquina",
        "Tríceps Cross Barra Reta",
        "Tríceps Barra Curva Cross",
        "Tríceps Inverso (Unilateral)",
        "Tríceps Inverso Cross",
        "Supino Fechado",
        "Mergulho no Banco",
        "Rosca Direta (Barra Reta/W)",
        "Rosca Alternada (Halteres)",
        "Rosca Alternada (Banco Inclinado)",
        "Rosca Martelo (Hammer Curl)",
        "Rosca Scott (Banco)",
        "Rosca Scott (Barra W)",
        "Rosca Scott (Halteres)",
        "Rosca Scott Máquina",
        "Rosca Concentrada",
        "Rosca 21",
        "Rosca Spider",
        "Rosca Inclinada",
        "Rosca Zottman",
        "Rosca Inversa (Barra)",
        "Rosca Cross (Corda)",
        "Rosca Articulada Máquina",
        "Flexão/Extensão de Punho",
        "Rosca Punho"
    ],
    "Abdômen": [
        "Crunch (Supra)",
        "Crunch na Polia (Cable Crunch)",
        "Elevação de Pernas (Hanging Leg Raise)",
        "Abdominal Bicicleta",
        "Abdominal Canivete",
        "Abdominal Infra (Solo)",
        "Abdominal Infra Bola",
        "Abdominal Infra Paralela",
        "Abdominal Supra (Bola)",
        "Abdominal Supra Solo",
        "Abdominal Supra Banco Declinado",
        "Abdominal Remador",
        "Roda Abdominal (Ab Wheel)",
        "Prancha (Plank)",
        "Prancha Isométrica",
        "Prancha Iso Lateral",
        "Prancha Iso Ventral",
        "Infra Prancha",
        "Prancha Lateral",
        "Oblíquo Cross Polia Baixa",
        "Vácuo Abdominal (Stomach Vacuum)",
        "Woodchopper (Lenhador)"
    ],
    "Cardio": [
        "Esteira",
        "Bike / Bicicleta",
        "Elíptico",
        "Escada",
        "Corda Naval",
        "Pular Corda"
    ]
};

export const ROUTINE_TYPES = [
    {
        value: "Full Body",
        label: "Full Body (Corpo Inteiro)",
        description: "Treina todos os grandes grupos musculares em uma única sessão. Frequência: 3x/semana."
    },
    {
        value: "Upper/Lower",
        label: "Upper / Lower (Superiores / Inferiores)",
        description: "Dividido em superiores e inferiores. Frequência: 4x/semana."
    },
    {
        value: "PPL",
        label: "PPL (Push / Pull / Legs)",
        description: "Empurrar, Puxar e Pernas. Alta frequência."
    },
    {
        value: "Bro-Split",
        label: "Bro-Split (Grupo Muscular Isolado)",
        description: "Foca em um ou dois grupos musculares por dia. Baixa frequência por músculo."
    },
    {
        value: "Arnold Split",
        label: "Arnold Split (Agonista / Antagonista)",
        description: "Agrupa músculos opostos (Peito/Costas, etc)."
    },
    {
        value: "PHUL",
        label: "PHUL (Power Hypertrophy Upper Lower)",
        description: "Mistura força e hipertrofia com divisão Upper/Lower."
    },
    {
        value: "Personalizado",
        label: "Personalizado",
        description: "Crie sua própria divisão de treino."
    }
];
